version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(filename)s:%(lineno)d"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: ${logs_dir}/app.log
    encoding: utf8

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: error
    filename: ${logs_dir}/error.log
    encoding: utf8

loggers:
  '':
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no

  training:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no

  data_management:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no

  evaluation:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no

  inference:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no 